config/routes.rb
ChalkboardApp::Application.routes.draw do
  get "error/index"
  mathjax 'mathjax'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "students/new"
  get "static_pages/home"
  get "static_pages/help"
  post "static_pages/contact"
  resources :students
  match '/signup', to: 'students#new', via: 'get'
  match '/activations/:id' => "activations#update", :via => ['get','post']
  get "questions/student_answer_create"

  resources :exams
  resources :downloads 
  get "questions/check_solution"
  resources :reports
  get 'subjects/:subject/:module_test' => 'subjects#show'

  get 'subjects/:subject' => 'subjects#index'
  resources :trackings
  get 'questions/:subject/:module_test/:module_test_name/:number' => 'questions#show'

  match 'pins/:pin/:student/:subject/:activity' => 'pins#show', :via => ['get']
  match 'attendees/:id/:subject' => 'attendees#other', :via => ['get']
  resources :attendees
  resources :classrooms
  resources :pins
  resources :error  
  resources :results
  resources :subscriptions
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/report/module', to: 'reports#module_index', via: 'get'
  match '/report/test', to: 'reports#test_index', via: 'get'
  
  match '/student_reset_password', to: 'students#student_reset_password',     via: 'post'
  match '/student_reset_password', to: 'students#student_reset_password',     via: 'get'
  match '/forget_password', to: 'students#forget_password',     via: 'post'
  match '/forget_password', to: 'students#forget_password',     via: 'get'
  match '/reset_password', to: 'sessions#reset_password',     via: 'post'

   root 'static_pages#home'

  

end

app/models/student.rb
require 'valid_email'
class Student < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :nickname, presence: true, length: { maximum: 50 }
  validates :email, presence: true, :email => true

  has_secure_password
  
  validates :password, :length => { :within => 6..40 }, :if => :password_blank?

  validates_confirmation_of :password,
    if: lambda { |m| m.password.present? }
 
  has_many :trackings 
  has_many :results
  has_many :questions, through: :results

  has_many :attendees
  has_many :classrooms, :through => :attendees

  def password_blank?
    
    !@password.blank?
  end

  def custom_update_attributes(params)
        

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
      update_attributes params
    end
  end

  def Student.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def generate_token(column)


    self[column] = SecureRandom.urlsafe_base64
  end

  def Student.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      
      self.remember_token = Student.encrypt(Student.new_remember_token)
      self.activation_token = generate_token(:activation_token)
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :signed_in_student, only: [:edit, :update]
  before_action :correct_student,   only: [:edit, :update]
  skip_before_filter :verify_authenticity_token
  def new
    if !signed_in? 
      @student = Student.new
    else
      redirect_to static_pages_home_path 
    end  
  end

  def show
    @student = Student.find(params[:id])	
  end

  def create
    nick = params[:student][:email].split("@")[0] 
    if !Student.all.collect(&:email).include? params[:student][:email]
      @student = Student.new(:nickname => nick, :email =>params[:student][:email], :password => params[:student][:password], :password_confirmation => params[:student][:password_confirmation])
      if @student.save
        StudentMailer.activation(@student).deliver
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def edit  
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @values = student_update_params

    respond_to do |format|
      format.js
    end
  end
  def student_reset_password
    if (params[:confirm_password]==params[:password] && params[:password].length>=6)
      @student=Student.find(params[:id])
      @student.password=params[:password]
      @student.password_confirmation=params[:confirm_password]
      @student.save
    end  
    respond_to do |format|
      format.js
    end
  end
  def forget_password
     @student = Student.new
  end
  private
    def student_params
      params.require(:student).permit(:email, :password,
                                   :password_confirmation)
    end

    def student_update_params
       params.require(:student).permit(:nickname, :email, :first, :gender,
                                   :password, :password_confirmation,
                                   :last, :age, :school, :grade, :island)
    end

   def signed_in_student
     puts signed_in?
     unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
   end

    def correct_student
      @student = Student.find(params[:id])
      redirect_to(root_url) unless current_student?(@student)
    end
end

app/helpers/students_helper.rb
module StudentsHelper

	def profile
		if Student.where(:id => 66).pluck(:first)[0].nil?
			msg = "Please complete your profile!"
                elsif Student.where(:id => 66).pluck(:last)[0].nil?
                        msg = "Please complete your profile!"
                elsif Student.where(:id => 66).pluck(:age)[0].nil?
                        msg = "Please complete your profile!"
                elsif Student.where(:id => 66).pluck(:school)[0].nil?
                        msg = "Please complete your profile!"
                elsif Student.where(:id => 66).pluck(:grade)[0].nil?
                        msg = "Please complete your profile!"
                elsif Student.where(:id => 66).pluck(:island)[0].nil?
                        msg = "Please complete your profile!"
                elsif Student.where(:id => 66).pluck(:gender)[0].nil?
                        msg = "Please complete your profile!"
		else
			msg = ""
		end
	end

end

app/views/students/create.js.erb
<% if @student.nil? %>
  $("#signup-error").html("You're already registered. Please Sign In");
<% else %>
  <% if @student.save %>
  
    $(".whitePopUpSignIn").hide();
    $(".whitePopUp").hide();
    $(".popUpConfirm").show();
  <% end %>
  
  <% if !@student.errors.messages[:email].nil? && !@student.errors.messages[:password].nil? %>
    <%if params[:signup].blank?%>
      $("#signup-error").html("Email can't be blank <br/> Password can't be blank");
      $("#signupPopup-error").empty();
    <%else%>  
      $("#signupPopup-error").html("Email can't be blank <br/> Password can't be blank").setAttribute("style", "color:red;color:red;font-size:13px;font-weight: bold;");
      $("#signup-error").empty();
    <%end%>
    
  <% elsif !@student.errors.messages[:email].nil? && !@student.errors.messages[:password].nil? %>
    <%if params[:signup].blank?%>
      $("#signup-error").html("Email <%= @student.errors.messages[:email][0] %> <br/> Password <%=@student.errors.messages[:password][0] %>");
      $("#signupPopup-error").empty();
    <%else%>  
      $("#signupPopup-error").html("Email <%= @student.errors.messages[:email][0] %> <br/> Password <%=@student.errors.messages[:password][0] %>").setAttribute("style", "color:red;color:red;font-size:13px;font-weight: bold;");
      $("#signup-error").empty();
    <%end%>
    
  <% elsif !@student.errors.messages[:email].nil? %>
    <%if params[:signup].blank?%>
      $("#signup-error").html("Email <%= @student.errors.messages[:email][0] %>");
      $("#signupPopup-error").empty();
    <%else%>  
      $("#signupPopup-error").html("Email <%= @student.errors.messages[:email][0] %>").setAttribute("style", "color:red;color:red;font-size:13px;font-weight: bold;");
      $("#signup-error").empty();
    <%end%>
    
  <% elsif !@student.errors.messages[:password].nil? %>
    <%if params[:signup].blank?%>
      $("#signup-error").html("Password <%=@student.errors.messages[:password][0] %>");
      $("#signupPopup-error").empty();
    <%else%>  
      $("#signupPopup-error").html("Password <%=@student.errors.messages[:password][0] %>");
      $("#signup-error").empty();
    <%end%>
    
  <% elsif !@student.errors.messages[:password_confirmation].nil? %>
    <%if params[:signup].blank?%>
      $("#signup-error").html("Password doesn't match");
      $("#signupPopup-error").empty();
    <%else%>  
      $("#signupPopup-error").html("Password doesn't match");
      $("#signup-error").empty();
    <%end%>
    
  <% end %>
<% end %>

app/views/students/edit.html.erb
      <div class="popUpConfirm">
        <h5>Are you sure</h5>
        <div class="buttonsPopup">
          <%= link_to "Submit",nil, :id=> "submit_edit_form" %>
          <a href="#" class="GoBack" title="Go Back">Cancel</a></div>
      </div>

      <div class="subscription_error" style="display:none;">
        <h5> </h5>
        <div class="buttonsPopup">
        <a href="#" class="GoBack" title="Go Back">Submit</a></div>
      </div>

      <section class="profile">
        <div class="dTab"></div>
        <h2>This is You!</h2>
        <p class="centerText"></p>
        <%= form_for @student, :html => {:class => "profileData"} do |f|  %>
          <div class="formRow">
            <label style="text-align:right;">Nickname</label>
            <span><span class="dividerFormCol">&nbsp;</span></span>
            <div class="secondColForm">
              <%= f.text_field :nickname %>
            </div>
            <div class="cBoth"></div>
          </div>

          <div class="formRow">
            <label style="text-align:right;">E-mail</label>
            <span class="dividerFormCol">&nbsp;</span>
            <div class="secondColForm yellow"><%= f.text_field :email %></div>
            <div class="cBoth"></div>
            <div class="cBoth"></div>
          </div>
          <div class="formRow">
            <label style="text-align:right;">First Name </label>
            <span><span class="dividerFormCol">&nbsp;</span></span>
            <div class="secondColForm">
              <%= f.text_field :first %>
            </div>
            <div class="cBoth"></div>
          </div>

          <div class="formRow">
            <label style="text-align:right;">Last Name </label>
            <span class="dividerFormCol">&nbsp;</span>
            <div class="secondColForm">
              <%= f.text_field :last %>
            </div>
            <div class="cBoth"></div>
          </div>
          <div class="formRow mT">
            <label style="text-align:right;">Age </label>
            <span class="dividerFormCol"></span>
            <div class="secondColForm small">
              <%= f.select :age, options_for_select(["12","13","14","15","16","17","18", "19" ],:selected=>@student.age)%>
              <img src="/assets/customSelect_small.png"></div>
            <div class="cBoth"></div>
          </div>
          <div class="formRow mT">
            <label style="text-align:right;">Gender </label>
            <span class="dividerFormCol"></span>
            <div class="secondColForm small">
              <%= f.select :gender, options_for_select(["boy", "girl" ],:selected=>@student.gender)%>
              <img src="/assets/customSelect_small.png"></div>
            <div class="cBoth"></div>
          </div>
          <div class="formRow mT">
            <label style="text-align:right;">School </label>
            <span class="dividerFormCol"></span>
            <div class="secondColForm">
            <%= f.select :school, options_for_select( ["Abaco Central High", "Abraham's Bay High", "Acklins Central High", "Agape Christian All Age", "Alpha Omega Christian", "Aquinas College", "Arhtur's Town High", "Bahamas Academy", "Bimini All Age", "Bishop Michael Eldon", "Black Point All Age", "Blairwood Academy", "C.C. Sweeting", "C.I. Gibson Senior", "C.R. Walker Senior", "C.V. Bethel Senior", "Calvary Academy", "Central Andros High", "Central Eleuthera High", "Crooked Island High", "Doris Johnson Senior", "Eight Mile Rock High", "Faith Temple Christian Academy", "Farmer's Cay All Age", "Freeport Gospel Chapel", "Galilee Academy", "Gateway Christian Academy", "Government High", "Grand Bahama Academy", "Grand Bahama Catholic", "Grand Cay All Age", "Harbour Island All Age", "Holy Name Catholic", "Inagua All Age", "Jack Hayward High", "Jordan Prince William", "Kingsway Academy", "L.N. Coakley High", "Long Cay All Age", "Lucaya International", "Lyford Cay", "Magrove Cay High", "Man-O-War Cay All Age", "Mary E Albury High", "Moores Island All Age", "Mt Caramel Preparatory Academy", "N.G.M Major High", "Nassau Christian Academy", "North Andros High", "North Eleuthera High", "North Long Island High", "Old Bight High", "Preston Albury High", "R.M. Bailey Senior", "R.N. Gomez All Age", "Ragged Island All Age", "Rum Cay All Age", "San Salvador High", "Sherlin Bootle High", "Sound Andros High", "Spanish Wells All Age", "St Andrews Anglican", "St Andrews School", "St Anne's Catholic", "St Anne's School", "St Augustine's College", "St Francis De Sales All Age", "St George's High", "St John's College", "St Paul's Methodist College", "St Vincent de Paul", "Staniel Cay All Age", "Sunland Baptist Academy", "Sweeting's Cay All Age", "Tabernacle Christian Academy", "Tambearly", "The Dunmore School", "The Island School", "Wesley College", "Westminster College", "Windermore High"],:selected=>@student.school )  %>
             <img src="/assets/customSelect.png"></div>
            <div class="cBoth"></div>
          </div>
          <div class="formRow mT">
            <label style="text-align:right;">Grade </label>
            <span class="dividerFormCol"></span>
            <div class="secondColForm small">
              <%= f.select :grade,options_for_select(["9","10","11","12"],:selected=>@student.grade)%>
            
              <img src="/assets/customSelect_small.png"></div>
            <div class="cBoth"></div>
          </div>
          <div class="formRow mT">
            <label style="text-align:right;">Island </label>
            <span class="dividerFormCol"></span>
            <div class="secondColForm" style="max-height: 100px; !important;">

            <%= f.select :island, options_for_select(["Abaco", "Acklins", "Andros", "Berry Islands", "Bimini Islands", "Cat Island", "Crooked Island", "Eleuthera", "Exuma", "Grand Bahama", "Long Island", "Mayaguana", "New Providence", "Ragged Island", "Rum Cay", "San Salvador"],:selected=>@student.island) %>
              <img src="/assets/customSelect.png"></div>
            <div class="cBoth"></div>
          </div>
          
          <div class="btn"><a href="#" class="commitChanges" title="Commit Change" rel="Commit Change">Submit</a></div>
	<div></div>
    <% end %>
      </section>
    

<script>
  $( document ).ready(function() {
    $("#submit_edit_form").click(function(){
      var student_id = "<%= params[:id] %>"
      $.ajax( {
        type: "PUT",
        url: "/students/"+student_id,
        data: $('.profileData').serialize(),
        success: function( response ) {
          return false;
        }
      });
    });
  });
</script>
<style>
div.fancy-select {
  position: relative;
  font-size: 18px;
  color: #46565D;
}

div.fancy-select.disabled {
  opacity: 0.5;
}



div.fancy-select div.trigger {
  border-radius: 4px;
  cursor: pointer;
  padding: 7px 24px 7px 9px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  position: relative;
  width: 272px;
  font-family:open_sanslight;
  font-size:20px;
  font-weight:normal;
  color:#343434;
  text-transform:none;
  background:url("../images/sprite_1.png") no-repeat scroll -7px -268px rgba(0, 0, 0, 0);
}


div.fancy-select ul.options {
  border-radius: 4px;
  box-shadow: 2px 1px 12px #000000;
  left: 0;
  list-style: none outside none;
  margin: 0;
  max-height: 100px;
  min-width: 310px;
  opacity:0;
  overflow: auto;
  padding: 1px 0;
  position: absolute;
  text-align: left;
  top: 40px !important;
  visibility:hidden;
  z-index: 50;
}

div.fancy-select ul.options.open {
  visibility: visible;
  top: 50px;
  opacity: 1;
}

div.fancy-select ul.options.overflowing {
  top: auto;
  bottom: 40px;

  transition: opacity 300ms ease-out, bottom 300ms ease-out, visibility 300ms ease-out;
  -webkit-transition: opacity 300ms ease-out, bottom 300ms ease-out, visibility 300ms ease-out;
  -moz-transition: opacity 300ms ease-out, bottom 300ms ease-out, visibility 300ms ease-out;
  -ms-transition: opacity 300ms ease-out, bottom 300ms ease-out, visibility 300ms ease-out;
  -o-transition: opacity 300ms ease-out, bottom 300ms ease-out, visibility 300ms ease-out;
}

div.fancy-select ul.options.overflowing.open {
  top: auto;
  bottom: 50px;

  transition: opacity 300ms ease-out, bottom 300ms ease-out;
  -webkit-transition: opacity 300ms ease-out, bottom 300ms ease-out;
  -moz-transition: opacity 300ms ease-out, bottom 300ms ease-out;
  -ms-transition: opacity 300ms ease-out, bottom 300ms ease-out;
  -o-transition: opacity 300ms ease-out, bottom 300ms ease-out;
}

div.fancy-select ul.options li {
  padding:12px;
  background:#fff;
  border-top: 1px solid #999999;
  color: #323232;
  padding: 10px 15px;
  transition: all 150ms ease-out;
  -webkit-transition: all 150ms ease-out;
  -moz-transition: all 150ms ease-out;
  -ms-transition: all 150ms ease-out;
  -o-transition: all 150ms ease-out;
  font-size:18px;
}
div.fancy-select ul.options li.hover {
  background: #51D3DA;
}
</style>

app/views/students/forget_password.html.erb
<section>
<div class="whitePopUpSignIn forgot_password_reset" style="position:fixed; margin-left: 33%; margin-top: 5%; margin-left: 33%; margin-top: 5%;"> 
        
       <%= form_tag student_reset_password_path,:method=>"post",:class=>"reset_new" do %>
        <div id="reset-password-error" style="color:red;color:red;font-size:13px;font-weight: bold;"></div>
         
          <p>
            <label style="text-align: right; margin-left: -10px;">New Password</label>
            <%=password_field_tag 'password',class: "i1", placeholder: "*",style:"margin-left: 10px;"%>
          </p>
          <p class="label">
            <label></label>
            <span>enter password</span>
          </p>
          <p>
            <label style="text-align: right; margin-left: -10px;">Confirm Password</label>
            <%= password_field_tag 'confirm_password',placeholder: "*",style:"margin-left: 10px;" %>
          </p>
          <p class="label">
            <label></label>
            <span>reenter password</span>
          </p>
        
         <%=hidden_field_tag "id",params[:id]%>
         <br/>
         <p class="btnPanel">
           <p class="btnPanel"><a href="#" class="yallowBtn reset_new_path padding-set" rel="Log In">reset</a></p>
        
         </p> 
         <br/>
      <% end %>
      
      </div>


      <p class="centerText" style="display:none;">
            <a class="forgetP in popup" rel="forgot_password_reset" href="#" title="Forget Passsword?" id="foofaa">Forget Passsword?</a>
          </p>
  </section>

<script>
$(document).ready(function() {
  $('#foofaa a').trigger('click');
  $(".reset_new_path").click(function(){

      $.ajax( {
        type: "POST",
        url: "/student_reset_password",
        data: $('.reset_new').serialize(),
        success: function( response ) {
          return false;
        }
    });
  });  
});
</script>

app/views/students/new.html.erb
<section>
<div class="whitePopUpSignIn invitePopUpSignup forgot_password_reset" style="position:fixed; margin-left: 33%;margin-left: 34%;"> 

      <%= form_for(@student, :html => {:class => "signup_header",:style=>"margin-top: 30px;"} ) do |f| %>
            <div id="signupPopup-error" style="color:red;color:red;font-size:13px;font-weight: bold;"></div>
              <p>
                <label style="text-align: right;margin-left: 19px;">Nickname</label>
                <%= f.text_field :nickname, class: "i1",style:" margin-left:21px;" %>
              </p>
              <p class="label" style="margin-left: 10%;">
                <label></label>
                <span>enter nickname</span></p>
              <p>
                <label style="text-align: right;margin-left: 27px;" >Email</label>
                <%= f.text_field :email, class: "i1",style:" margin-left:10px;"%>
              </p>
              <p class="label" style="margin-left: 10%;">
                <label ></label>
                <span>enter email address</span></p>
              <p>
                <label style="text-align: right;margin-left: 19px;">Password</label>
                <%= f.password_field :password, class: "i1",style:" margin-left:21px;" %>
              </p>
              <p class="label" style="margin-left: 10%;">
                <label></label>
                <span>enter password</span></p>
              <p>
                <label style="text-align: right;margin-left: -5px">Confirmation</label>
                <%= f.password_field :password_confirmation, class: "i1",style:" margin-left:40px;" %>
              </p>
              <p class="label" style="margin-left: 10%;">
                <label style="text-align:right;"></label>
                <span>reenter password</span></p>
               <p class="customRadio">
                <label></label>
                <span><b class="checked"></b>
                <input type="radio" checked="checked" name="inviteRadio" />
                BGCSE</span><span>
                </p>
                <br/>
                <%=hidden_field_tag "signup","signup"%>
                <p class="btnPanel"><a href="#" class="yallowBtn signup_header_path padding-set" >Submit</a>
                <a href="#" class="grayBtn reset reset_signup_popup padding-set">Reset</a></p>
                </p>
            <br/>    
          <% end %>
        

      </div>


      <p class="centerText" style="display:none;">
        <a class="forgetP in popup" rel="forgot_password_reset" href="#" title="Forget Passsword?" id="foofaa">Forget Passsword?</a>
      </p>
  </section>
  
<script>
$(document).ready(function() {
  $('#foofaasignup a').trigger('click');
  $(".signup_header_path").click(function(){
    $.ajax( {
      type: "POST",
      url: "/students",
      data: $('.signup_header').serialize(),
      success: function( response ) {
        return false;
      }
      
    } );
     return false; 
  });
});
</script>
<style>
  h3 {
    color: #343434;
    font-family: amatic_scbold;
    font-size: 47px;
    font-weight: normal;
    line-height: 0;
    margin-right: 20px;
    margin-top: 19px;
    text-align: center;
}
 
</style>

app/views/students/show.html.erb
<section>
<div class="leftSection"> <img src="/design/images/map.png" class="map" title="Map" alt="Map" />
<article class="aboutUs">
  <div class="yellowTextTitle caps">About Us</div>
<div class="caps">242Chalkboard is an educational platform for BGCSE test preparation.  At 242Chalkboard we maximize the success of the Bahamian student by leveraging technology to prepare them to be game changers of tomorrow.  All of the sites resources are available to all students to facilitate their preparation for their upcoming examinations.  Our solutions serve all Bahamian students from Grand Bahama to Inagua.</div>
</article>
</div>
<div class="rightSection">
<h1 style="color:white;">You really CAN do whatever you WANT.</h1>
<h2>Take your BGCSE with Confidence.</h2>
<div class="benifits">
  <div class="examPappers" rel="PAST EXAM PAPERS">PAST EXAM PAPERS</div>
  <div class="improveGrades" rel="Improve grades">Improve grades</div>
  <div class="available" rel="Available 24/7">Available 24/7</div>
  <p class="cBoth"></p>
</div>
<div class="cBoth"></div>
<br/>
<br/>
<div class="yellowTextTitle size15">What’s Special about 242Chalkboard?</div>
<div class="caps size15">242Chalkboard is the most comprehensive collection of BGCSE study resources on the web offering practice modules and exams with step by step solutions to help you succeed on your BGCSE exam!  Our extensive core and extended papers in a convenient easy to follow "study guide" format presents a comprehensive overview of the topics involved in the BGCSE.  Our database of past examinations is continually expanding, keeping you up-to-date on the latest BGCSE testing.</div>
</div>
</section>

app/views/students/student_reset_password.js.erb
<%if !@student.blank?%>
  
	window.location.href="<%=static_pages_home_path(:note=>"reset password")%>"
<%else%>
	<%if(params[:confirm_password]!=params[:password])%>
	$("#reset-password-error").html("Password doesn't match");
	<%elsif (params[:confirm_password].blank? && params[:password].blank?)%>
	$("#reset-password-error").html("Password cant be blank");
	<%elsif (params[:confirm_password].blank?)%>
	$("#reset-password-error").html("Password cant be blank");
	<%elsif (params[:password].blank?)%>
	$("#reset-password-error").html("Password cant be blank");
	<%else%>
	 $("#reset-password-error").html("Password is too short (minimum is 6 characters)");
	<%end%>
<%end%>

app/views/students/update.js.erb
<% if @values.values.include? "" %>
  $(".subscription_error h5").html("Please fill All the Fields");
  $(".subscription_error").css("display", "block");
<% elsif @values[:password] != @values[:password_confirmation] %>
  $(".subscription_error h5").html("Password doesn't match");
  $(".subscription_error").css("display", "block");
<% else %>
  <% @student.update_attributes(@values) %>
  <% flash[:success] = "Profile updated" %>
  window.location = "/students/<%= @student.id %>"
<% end %>