config/routes.rb
ChalkboardApp::Application.routes.draw do
  get "error/index"
  mathjax 'mathjax'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "students/new"
  get "static_pages/home"
  get "static_pages/help"
  post "static_pages/contact"
  resources :students
  match '/signup', to: 'students#new', via: 'get'
  match '/activations/:id' => "activations#update", :via => ['get','post']
  get "questions/student_answer_create"

  resources :exams
  resources :downloads 
  get "questions/check_solution"
  resources :reports
  get 'subjects/:subject/:module_test' => 'subjects#show'

  get 'subjects/:subject' => 'subjects#index'
  resources :trackings
  get 'questions/:subject/:module_test/:module_test_name/:number' => 'questions#show'

  match 'pins/:pin/:student/:subject/:activity' => 'pins#show', :via => ['get']
  match 'attendees/:id/:subject' => 'attendees#other', :via => ['get']
  resources :attendees
  resources :classrooms
  resources :pins
  resources :error  
  resources :results
  resources :subscriptions
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/report/module', to: 'reports#module_index', via: 'get'
  match '/report/test', to: 'reports#test_index', via: 'get'
  
  match '/student_reset_password', to: 'students#student_reset_password',     via: 'post'
  match '/student_reset_password', to: 'students#student_reset_password',     via: 'get'
  match '/forget_password', to: 'students#forget_password',     via: 'post'
  match '/forget_password', to: 'students#forget_password',     via: 'get'
  match '/reset_password', to: 'sessions#reset_password',     via: 'post'

   root 'static_pages#home'

  

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :sign_in_user

  include SubjectsHelper

  def show
    if params[:sort_by].nil?
      track = Tracking.where(:student_id => current_student.id, :subject => params[:subject], :module_test => params[:module_test], :module_test_name => params[:module_test_name]).first
    else
      track = Tracking.where(:student_id => current_student.id, :subject => params[:subject], :module_test => params[:module_test]).first
    end

    if track.nil?
      @i = 1
    else
      @i = track.question
    end

    @which = params[:module_test]

    
    @statistics = show_all(params[:subject],params[:module_test])
  
    @locked = "no"
    registered_date = Subscription.where(:student_id => current_student.id, :subject => params[:subject]).pluck("created_at").sort.last
   
      if registered_date.nil?
        @locked = "yes"
      else
        if (registered_date.to_datetime + 365.days) < DateTime.now
          @locked = "yes"
        end
      end

    if !params[:sort_by].nil?
      respond_to do |format|
        format.js
      end
    end 

  end


  def index

    @module_stats = pie_chart(params[:subject],"module")
    @test_stats = pie_chart(params[:subject],"test")

    @module_top_five = top_five(params[:subject],"module")
    @test_top_five = top_five(params[:subject],"test")

  end

 def sign_in_user
    if !signed_in?
      redirect_to signin_path
    end
  end


end

app/helpers/subjects_helper.rb
module SubjectsHelper

  def show_all(subject,module_test)

    statistics = Hash.new
    total_module = Question.where(:subject => subject, :module_test => module_test).count
    complete_module = Result.where(:subject => subject, :module_test => module_test).collect(&:student_answer).compact.count

    @complete_percent_module = ((complete_module.to_f/total_module.to_f) * 100).round(1)
    if @complete_percent_module.nan?
      @complete_percent_module=0.0
    end  
    list = Question.where(:subject => subject,:module_test => module_test).order("module_test_name").pluck("DISTINCT module_test_name")

    total_by_result_module = Result.where(:subject => subject, :module_test => module_test).count

    complete_true_module = Result.where(:subject => subject, :module_test => module_test, 
                                        :correct => true, :student_id => current_student.id).count

    @complete_true_percent_module = ((complete_true_module.to_f/total_by_result_module.to_f) * 100).round(1)
    if @complete_true_percent_module.nan?
      @complete_true_percent_module=0.0
    end  
    
    list.each do |i|
      stats = Hash.new
      total = Question.where(:subject => subject, :module_test => module_test, :module_test_name => i).count
      answered=  Result.where(:subject => subject, :module_test => module_test, :module_test_name => i, :student_id => current_student.id).collect(&:student_answer).compact.count
      
      stats["answered"] = answered
      stats["unanswered"] = total - answered
  
      correct = Result.where(:subject => subject, :module_test => module_test, :module_test_name => i, :correct => true, :student_id => current_student.id).count
      stats["correct"] = correct
      stats["incorrect"] = total - correct
     

      statistics[i] = stats

    end

    if params[:sort_by] == "Completed"
      puts "YES" 
      stat_arr = statistics.to_a

      (0..(statistics.count-1)).each do |input|
        
        if !stat_arr[input+1].nil?
          
          if ((100/(stat_arr[input+1].second["unanswered"]+stat_arr[input+1].second["answered"]))*stat_arr[input+1].second["answered"]).to_f.round(2)> ((100/(stat_arr[input].second["unanswered"]+stat_arr[input].second["answered"]))*stat_arr[input].second["answered"]).to_f.round(2)
            a = stat_arr[input]
            stat_arr[input] = stat_arr[input+1]
            stat_arr[input+1] = a
          end
        end
      end
      
      temp = Hash.new
      stat_arr.each do |key, value|
    	item = key
	puts key
      	total = Question.where(:subject => subject, :module_test => module_test, :module_test_name => item).count 
     	puts total
	value.each do |k,v| 
		if k.eql? "answered"
			puts v
			if v.to_i > 0
				temp[key] = (v.to_f/total.to_f).round(2)
			else
				temp[key] = 0
			end
		end
        end
      end 

      stat = Hash[*stat_arr.flatten]
      stat2 = Hash.new
      tmp_new = Hash.new
      tmp_new = temp.sort_by {|_key, value| value}.reverse
      tmp_new.each do |k,v|
	stat2[k] = stat[k] 

      end

      statistics = stat2
    end

    if params[:sort_by] == "result"
      stat_arr = statistics.to_a

      (0..(statistics.count-1)).each do |input|

        if !stat_arr[input+1].nil?

          if ((100/(stat_arr[input+1].second["unanswered"]+stat_arr[input+1].second["answered"]))*stat_arr[input+1].second["correct"]).to_f.round(2)> ((100/(stat_arr[input].second["unanswered"]+stat_arr[input].second["answered"]))*stat_arr[input].second["correct"]).to_f.round(2)
            a = stat_arr[input]
            stat_arr[input] = stat_arr[input+1]
            stat_arr[input+1] = a
          end
        end


      temp = Hash.new
      stat_arr.each do |key, value|
        item = key
        puts key
        total = Question.where(:subject => subject, :module_test => module_test, :module_test_name => item).count
        puts total
        value.each do |k,v|
                if k.eql? "correct"
                        puts v
                        if v.to_i > 0
                                temp[key] = (v.to_f/total.to_f).round(2)
                        else
                                temp[key] = 0
                        end
                end
        end
      end

      stat = Hash[*stat_arr.flatten]
      stat2 = Hash.new
      tmp_new = Hash.new
      tmp_new = temp.sort_by {|_key, value| value}.reverse
      tmp_new.each do |k,v|
        stat2[k] = stat[k]

      end

      statistics = stat2

      end

    end

    return statistics
  end

  def pie_chart(subject,module_test)
    
    total_module = Question.where(:subject => subject, :module_test => module_test).count
    complete_module = Result.where(:subject => subject, :module_test => module_test,:student_id=>current_student.id).collect(&:student_answer).compact.count
    incomplete_module = total_module - complete_module
    
    complete_percent_module = ((complete_module.to_f/total_module.to_f) * 100).round(1)
    incomplete_percent_module = ((incomplete_module.to_f/total_module.to_f) * 100).round(1)

    total_by_result_module = Result.where(:subject => subject, :module_test => module_test, :student_id => current_student.id).collect(&:student_answer).compact.count
    complete_true_module = Result.where(:subject => subject, :module_test => module_test, 
                                      :correct => true, :student_id => current_student.id).count
    complete_false_module = Result.where(:subject => subject, :module_test => module_test, 
                                         :correct => false, :student_id => current_student.id).count

    complete_true_percent_module = ((complete_true_module.to_f/total_module.to_f) * 100).round(1)
    if complete_true_percent_module.nan?
      complete_true_percent_module=0.0
    end  
    complete_false_percent_module = ((complete_false_module.to_f/total_module.to_f) * 100).round(1)
    
    stats = {}
    stats["complete_module"] = complete_module
    stats["incomplete_module"] = incomplete_module
    stats["complete_percent_module"] = complete_percent_module
    stats["complete_true_module"] = complete_true_module
    stats["complete_false_module"] = total_module - complete_true_module
    stats["complete_true_percent_module"] = complete_true_percent_module
    stats["complete_false_percent_module"] = complete_false_percent_module

   return stats

  end

  def top_five(subject,module_test)
    record = Hash.new

    list = Result.where(:subject => subject, :module_test => module_test).pluck("DISTINCT module_test_name")
 
    list.each do |i|
      right = Result.where(:subject => subject, :module_test => module_test, :correct => true, :student_id => current_student.id).count
      wrong = Result.where(:subject => subject, :module_test => module_test, :correct => false, :student_id => current_student.id).count
      record[i] = right - wrong
    end

    record.sort {|a1,a2| a2[1].to_i <=> a1[1].to_i }

    top_five = {}   
    count = 0
    record.each do |i,j|
      stats = Hash.new
      break if count == 4

      c = Result.where(:subject => subject, :module_test => module_test, 
                                      :module_test_name => i, :correct => true, :student_id => current_student.id).count
      stats["correct"] = c
      inc = Question.where(:subject => subject, :module_test => module_test, 
                                        :module_test_name => i).count

      stats["incorrect"] = inc - c	
      top_five[i] = stats
      count +=1

    end

    puts top_five
    return top_five
  end


end

app/views/subjects/_data_table.html.erb
<% current_uri = request.env['PATH_INFO'] %>
<% current_uri = URI.decode(current_uri)%>
<% path_url = current_uri %>
<% count = 0 %>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Attempted</th>
    <th>Accuracy</th>
    <th>Action</th>
    <% if path_url.ends_with?("test")%> 
      <th>&nbsp;</th>
    <% end %>  
  </tr>
</thead>

  <% @statistics.each_with_index do |stat,index| %>

    <%#=button_to i, {:controller => :questions, :action => 'show', :subject => "mathematics", 
     :module_test_name => i, :module_test => @which,:number => @i}, :form => {:name => 'go_module_test'}, :method => :get, :remote => true %>
      <tr>
        <td>
          <% if index+1 < 10 %>
            0<%= index+1 %>
          <% else %>
            <%= index+1 %>
          <% end %>
        </td>
        
        <td style="color:#343434 !important" ><%= stat[0] %></td>
        <td>
          <div class="progressBarBox">
            <div class="pb">
              <div class="progressBar yellowBar"><span class="yellow"><%= pie_chart_all(stat[1])["answered"] %></span>
                  <div class="prograssBarCode">
                    <div class="subMarksP"></div>
                    <div class="MarksP red" style="width:<%= pie_chart_all(stat[1])["total_answered_percentage"]%>%;"></div>
                      <img src="/assets/progress.png"/>
                  </div>
              <span class="white"><%= pie_chart_all(stat[1])["unanswered"] %></span>   
              </div>
              
               <div style="float: left; margin-left: 5px;">
                <span class="retake_test">[<%= (stat[1])["total_answered_percentage"]%>%]</span>
              <div>
            </div>
          </div>
        </td>
        <td><div class="progressBarBox">
            <div class="pb">
              <div class="progressBar"> <span class="subRed"><%= pie_chart_all(stat[1])["correct"] %></span>
                <div class="prograssBarCode">
                  <div class="subMarksP"></div>
                  <div class="MarksP red" style="width:<%= pie_chart_all(stat[1])["total_result_percentage"]%>%;"></div>
                  <img src="/assets/progress.png" />
                </div>
                <span class="white"><%= pie_chart_all(stat[1])["incorrect"] %></span>
              </div>
               
               <div style="float: left; margin-left: 5px;">
              
              <span class="retake_test">[<%=(stat[1])["total_result_percentage"]%>%]</span>
            </div>
            </div>
          </div>
        </td>
       

        <td width="130" style="font-family:open_sanssemibold;">
          <% if @locked == "no"%>
            <a href="#" class="retake-home Retake" title="Start" id ="<%=stat[0]%>" >Start</a> 

	  <%else %>
            <%if count == 0%>
            <a href="#" class="retake-home Retake" title="Start" id ="<%=stat[0]%>" >Start</a>
            <% else %>
              <%= link_to image_tag("/assets/unlock.png", height: '40px', width: '40px;'), new_subscription_path %>
	    <% end %>
     	
          <% end %>          
        </td>
            
       
      </tr>
            <% count = 1%>
    <% end %>
    
  </table style="padding-bottom:20px;">


<% if path_url.ends_with?("test")%>

<% count = 0 %>
<% fh = "private/" + params[:subject].downcase %>
<% list_dir = Dir.entries(fh)%>

<% arr = Array.new %>
<% list_dir.each_with_index do |item,index| %>
<% t = item.split("-")[2] %>
<% t = t.to_s.split(".")[0].to_s.split(" ")[2]%>
<% arr.push(t.to_i) %>
<% end %>
<% arr %>
<% arr = arr.uniq %>
<% arr = arr.sort %>


<h3 style="color:#ffd22b">Past Examination Papers</h3>
<br/>
<table style = "width:50%">
<tr>
<th>#</th>
<th>Name</th>
<th>Date</th>
<th>E-Book</th>
</tr>

<%indexs = 0 %>
<% arr.each do |val| %>
<% list_dir = Dir.glob(File.join(fh,"* #{val}.pdf"))%>
<% list_dir.sort.each_with_index do |item,index| %>
<% pass = item.split("/")[2] %>
<% if item.include? "pdf" %>
<% split_list = item.split("-")%>
<tr>
        <td style="padding-right:20px">
          <% if indexs+1 < 10 %>
            0<%= indexs+1 %>
          <% else %>
            <%= indexs+1 %>
          <% end %>
        </td>
<% indexs = indexs + 1 %>
<td style="color:#343434 !important">Paper <%= split_list[1] %></td>
<% x= split_list[2] %>
<td style="color:#343434 !important"><%= x.to_s.split(".pdf")[0] %></td>
<td>
<% aa = pass.split("-")[0] %><% bb = split_list[1] %><% cc = x.to_s.split(".pdf")[0].delete(" ")%>
<% zz = "/exams/" + aa.downcase + "/" + aa + "-"+ bb + "-" + cc + "/index.html"%>
          <% if @locked == "no"%>
            <%= link_to image_tag("/assets/data-edit.png", height: '20px', width: '20px;'), zz, :target => "_blank" %>
          <%else %>
            <%if count == 0%>
              <%= link_to image_tag("/assets/data-edit.png", height: '20px', width: '20px;'), zz, :target => "_blank" %>
            <% else %>
              <%= link_to image_tag("/assets/unlock.png", height: '40px', width: '40px;'), new_subscription_path %>
            <% end %>

          <% end %>

</td>
</tr>
<% count = 1 %>

<% end  %>
<% end %>
<% end %>

</table>

<% end %>



<script>
  $( document ).ready(function() {
    $(".retake-home").click(function(){
      var id =this.id;
      window.location = '/questions/<%=params[:subject]%>/<%= params[:module_test]%>/'+id+'/1';
     });
   });   
</script>

app/views/subjects/_data_table_narrow.html.erb
<% current_uri = request.env['PATH_INFO'] %>
<% current_uri = URI.decode(current_uri)%>
<% path_url = current_uri %>

<% count = 0 %>
<table width="100%" border="0" cellspacing="0" cellpadding="0" style="text-align:left">


  <% @statistics.each_with_index do |stat,index| %>

    <tr>
    <%#=button_to i, {:controller => :questions, :action => 'show', :subject => "mathematics", 
     :module_test_name => i, :module_test => @which,:number => @i}, :form => {:name => 'go_module_test'}, :method => :get, :remote => true %>
      <td>
      <p style="color:#343434 !important" >
          <% if index+1 < 10 %>
            0<%= index+1 %>
          <% else %>
            <%= index+1 %>
          <% end %>
        
        <%= stat[0] %></p>
          <div class="progressBarBox">
            <div class="pb">
              <div class="progressBar yellowBar" > <span class="yellow"> <%= pie_chart_all(stat[1])["answered"] %></span>
                  <div class="prograssBarCode">
                    <div class="subMarksP"></div>
                    <div class="MarksP red" style="width:<%= pie_chart_all(stat[1])["total_answered_percentage"]%>%;"></div>
                      <img src="/assets/progress.png"/>
                  </div>
              <span class="white"><%= pie_chart_all(stat[1])["unanswered"] %></span>   
              </div>
              
               <div style="float: left; margin-left:5px;">
                <span class="retake_test">[<%= (stat[1])["total_answered_percentage"]%>%]</span>
              <div>
            </div>
          </div>
        <div class="progressBarBox">
            <div class="pb">
              <div class="progressBar"> <span class="subRed"><%= pie_chart_all(stat[1])["correct"] %></span>
                <div class="prograssBarCode">
                  <div class="subMarksP"></div>
                  <div class="MarksP red" style="width:<%= pie_chart_all(stat[1])["total_result_percentage"]%>%;"></div>
                  <img src="/assets/progress.png" />
                </div>
                <span class="white"><%= pie_chart_all(stat[1])["incorrect"] %></span>
              </div>
              
               <% if path_url.ends_with?("test")%> 
                 <div style="float: left; margin-left: 15px;">
               <%else%>
                 <div style="float: left; margin-left: 21px;">
               <%end%>         
              <span class="retake_test">[<%=(stat[1])["total_result_percentage"]%>%]</span>
            </div>
            </div>
          </div>
        
       
        <p style="font-family:open_sanssemibold;">
          <% if @locked == "no"%>
            <a href="#" class="retake-home Retake" title="Start" id ="<%=stat[0]%>" >Start</a>
	  <%else %>
            <%if count == 0%>
            <a href="#" class="retake-home Retake" title="Start" id ="<%=stat[0]%>" >Start</a>
            <% else %>
              <%= link_to image_tag("/assets/unlock.png", height: '20px', width: '20px;'), new_subscription_path %>
	    <% end %>	
          <% end %>
	<br/>
	<br/>
        </p>
      </td>
      </tr>
            <% count = 1%>
    <% end %>
  </table style="padding-bottom:20px;">

<% if path_url.ends_with?("test")%>

<% count = 0 %>


<% fh = "private/" + params[:subject].downcase %>
<% list_dir = Dir.entries(fh)%>

<% arr = Array.new %>
<% list_dir.each_with_index do |item,index| %>
<% t = item.split("-")[2] %>
<% t = t.to_s.split(".")[0].to_s.split(" ")[2]%>
<% arr.push(t.to_i) %>
<% end %>
<% arr %>
<% arr = arr.uniq %>
<% arr = arr.sort %>

<h3 style="color:#ffd22b">Past Examination Papers</h3>
<br/>
<table cellspacing = "10px" style = "width:100%">
<tr>
<th>Name</th>
<th>Date</th>
<th>E-Book</th>
</tr>
<% arr.each do |val| %>
<% list_dir = Dir.glob(File.join(fh,"* #{val}.pdf"))%>
<% list_dir.sort.each_with_index do |item,index| %>
<% pass = item.split("/")[2] %>
<% if item.include? "pdf" %>
<% split_list = item.split("-")%>

<tr>
<td style="color:#343434 !important">Paper <%= split_list[1] %></td>
<%x = split_list[2]%>
<td style="color:#343434 !important"><%= x.to_s.split(".pdf")[0] %></td>
<td style="vertical-align:top;">
<% aa = pass.split("-")[0] %><% bb = split_list[1] %><% cc = x.to_s.split(".pdf")[0].delete(" ")%>
<% zz = "/exams/" + aa.downcase + "/" + aa + "-"+ bb + "-" + cc + "/index.html"%>
          <% if @locked == "no"%>

            <%= link_to image_tag("/assets/data-edit.png", height: '10px', width: '10px;'), zz, :target => "_blank"%>
          <%else %>
            <%if count == 0%>
              <%= link_to image_tag("/assets/data-edit.png", height: '10px', width: '10px;'), zz, :target => "_blank" %>
            <% else %>
              <%= link_to image_tag("/assets/unlock.png", height: '20px', width: '20px;'), new_subscription_path %>
            <% end %>

          <% end %>

</td>

</tr>
<% count = 1%>

<% end  %>
<% end %>
<% end %>
</table>
<% end %>

<script>
  $( document ).ready(function() {
    $(".retake-home").click(function(){
      var id =this.id;
      window.location = '/questions/<%=params[:subject]%>/<%= params[:module_test]%>/'+id+'/1';
     });
   });   
</script>

app/views/subjects/show.html.erb

<div id = 'question_section'>
      <section class="chooseModuleSection">
      <div class="dTab"></div>
        <div class="chooseModule mathSingle">
          <div class="chooseMHeader"> <!-- <a class="exportExcel">Export to Excel</a> -->
            <div class="labelsRight">
              <div class="markers">
                <label class="yellowB"></label>
                <span class="yellowLabel">Attempted</span>
                <label class="whiteB"></label>
                <span class="whiteLabel">Unattempted</span> </div>
              <div class="markers">
                <label class="redB"></label>
                <span class="redLabel">Correct</span>
                <label class="whiteB"></label>
                <span class="whiteLabel">Incorrect</span> </div>
            </div>
            <div class="selectModuleDrop" >
             
            </div>
	    <div class = 'table_wide'>	
            <div class="radioBtnGrp" >
              
              <span><b class="checked"></b>
                <input type="radio" checked="checked" name="sortByRadio" value="name" />
                Name</span>
              <span><b class=""></b>
                <input type="radio" name="sortByRadio" value="Completed" />
                Attempted</span>
              <span><b class=""></b>
                <input type="radio" name="sortByRadio" value="result" />
                Accuracy</span> 

            </div>
            <div class="dataTable">
              <%= render "data_table" %>
            </div>
            </div>
            <div class = 'table_narrow'><%= render "data_table_narrow" %></div>
          </div>
        </div>
      </section>

</div>


<script>
$("input:radio[name=sortByRadio]").click(function() {
    var value = $(this).val();
    console.log(value);
    $.ajax({
        type : 'GET',
        url : "/subjects/<%= params[:subject] %>/<%= params[:module_test] %>",
        data: {'sort_by' : value },
        success: function (data) {
	  }
        });

});
</script>

app/views/subjects/show.js.erb
$(".dataTable").html("<%= escape_javascript(render(:partial => 'data_table')) %>");